version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/myqpp

jobs:
  rubocop:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: update bundler to 2.0.2
          command: |
            gem install bundler -v '2.0.2'
      - run:
          name: bundle install
          command: |
            bundle install --path=vendor/bundle --path=vendor/bundle --jobs=4
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop

workflows:
  version: 2
  flows:
    jobs:
      - rubocop
